export const icons = {
    success: "verified_user",
    warning: "warning",
    settings: "settings",
    add_circle_outline: "add_circle_outline",
    eye: "visibility",
    time: "access_time",
    save: "save_outline",
    download: "file_download_outline",
    delete: "delete_outline",
    reset: "key_outline",
    close: "close_outline",
    "eye-slash": "visibility_off",
    error: "do_disturb_alt",
    error_alt: "block_outline",
    login: "login",
    filter_alt: "filter_alt",
    search: "search",
    double_arrow: "keyboard_double_arrow_right",
    arrow: "keyboard_arrow_right",
    queue: "queue",
    show_chart: "show_chart",
    people_alt: "people_alt",
    help_outline: "help_outline",
    account_circle: "account_circle",
    person: "person",
    apartment: "apartment",
    arrow_downward: "arrow_downward",
    arrow_upward: "arrow_upward",
    person_outline: "person_outline",
}

export const styles = {
    outline: "material-icons-outlined",
    default: "material-icons",
}
